### ISSUE TITLE
Not all lines listed in hook

### ISSUE THREAD

**Issue by LMCrashy** [devcat-studio/VSCodeLuaDebug#13]
Hi,
I've just started using VSCodeLuaDebug, integration is really straightforward, so I first wanted to say "Great Job!"

I've had some issues with the path, but re-formatting them to be like the one I use in my project solved everything.

**Now, I've got two more issues:**

**1-Only a few lines are listed in the "hookfunc", therefore I'm not able to put breakpoints properly.** 
The lines listed by the hookfunc are lua function calls on "self", (IE : self:doSomething()), every other line doesn't trigger anything.
If I change the line (in createPureBreaker() )
`debug_getinfo(2, 'Sl')`
To
`debug_getinfo(1, 'Sl')`
Every line got listed, setting breakpoints anywhere actually halts the program, but VS Code does not enter in the "breakpoint" state, I cannot step over or other stuff like that, and the arrow showing the current line isn't displayed.

**2-I cannot see my local/global variables**
VScode show a "loading" animation forever.
However adding some watched values is working properly.

I use lua embeded in a c++ application, I was using a custom made debugger until now, which worked fine, but, you know, maintaining a text editor and a debugger is a lot of work, so I decided to go for a VScode-based solution. I think I'm really close to have something working with your plugin, which is really cool.

Thanks.

**Comment by LMCrashy** [comment]
Hi,
Update on issue #1:
I use LuaJit instead of standard Lua in my project.
Using standard lua fixes the issue.
I have no clues why there is a difference in debug info retrieval using luajit, I guess it's doing too much optimizations on the bytecode.
Any hint would be appreciated but I guess I could find a fix on my side.
Thanks.

**Comment by lee-seungjae** [comment]
Thank you for your kind appreciation.

issue 1: Sorry, but I don't have any experience about LuaJit.
issue 2: I think it's because of some change in VSCode. I'll look into it soon.

**Comment by LMCrashy** [comment]
Thanks for your answer.
I managed to get the breakpoints working while changing the stack index, and that's great.

For the locals, I'm able to get some local variables of the debuggee script when playing with the stack position, but I can never obtain the local variables before the hook, so I guess it's not because of VSCode.
Maybe both luajit and the way I call scripts in my program are causing the issue, and If I ever find a solution, I'll publish it somewhere if it's relevant.
Thanks !

**Comment by Leadwerks** [comment]
Regarding skipped lines, I think I am experiencing the same thing:
https://github.com/devcat-studio/VSCodeLuaDebug/issues/23
